# Generated by Django 4.1.5 on 2023-01-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='no_of_emps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(help_text='Enter a branch location (e.g Nairobi)', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('ranch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('join_date', models.DateTimeField(null=True, verbose_name='date launched')),
                ('balance', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('Kshs', 'Kenya Shillings'), ('Dollar', 'US Dollars'), ('Euro', 'Euros'), ('Pound', 'Pounds')], default='Kshs', max_length=10)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.branch')),
            ],
        ),
    ]
