# Generated by Django 4.1.5 on 2023-01-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_branch_no_of_emps_alter_branch_branch_name_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='ranch_name',
            new_name='branch_name',
        ),
    ]
